name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install scango-lite
      run: go install github.com/vichekaoeun/scango-lite@latest
      
    - name: Run security scan
      run: scango-lite run
      
    - name: Fail if issues found
      run: |
        if [ $? -eq 1 ]; then
          echo "Security issues detected! Please fix before merging."
          exit 1
        fi